Client/Pages/Admin.cshtml.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Client.Pages
{
    public class AdminModel : PageModel
    {
        public string Output { get; private set; } = "";

        public void OnGet()
        {
            if ((Boolean)TempData.Peek("isAdmin"))
            {
                Reference refer = new Reference("http://localhost:5000/", new System.Net.Http.HttpClient());
                IDictionary<string, int> result = refer.AdminAsync().Result;
                if (result.Count != 0)
                {
                foreach (KeyValuePair<string, int> item in result)
                {
                    Output += item.Key + "\t" + item.Value.ToString("C", Globals.nfi) + "\n";
                }
                } else
                {
                    Output += "Nincs adat";
                }
            }
        }

        public void OnPost()
        {
            string input = Request.Form["pass"];
            if (input.Equals("f-original"))
            {
                TempData["isAdmin"] = true;
                Response.Redirect("admin");
            }
        }
    }
}

Client/Pages/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Globalization;

namespace Client.Pages
{
    public class DetailsModel : PageModel
    {
        public short Status { get; private set; } = 2;
        public string Output { get; private set; } = "";
        public string Balance { get; private set; } = "";

        public void OnGet()
        {
            if (TempData.Peek("username") != null)
            {
                string name = TempData.Peek("username").ToString();
                Reference refer = new Reference("http://localhost:5000/", new System.Net.Http.HttpClient());
                Status = 1;
                Output += name + " felhasználó egyenlege: ";
                int value = refer.DetailsAsync(name).Result;
                
                Balance += value.ToString("C", Globals.nfi);
            }
            else
            {
                Status = 0;
                Output += "Még nem regisztráltál!";
            }
        }
    }
}

Client/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Gazdalkodj_Client.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Client/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Client.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
            if (TempData.Peek("isAdmin") == null) TempData.Add("isAdmin", false);
        }
    }
}

Client/Pages/Register.cshtml.cs
using System;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Client.Pages
{
    public class RegisterModel : PageModel
    {
        public int ResponseCode { get; private set; } = 0;
        public string Output { get; private set; } = "";
        private bool createNew = true;

        public void OnGet()
        {
            if (TempData.Peek("username") != null)
            {
                ResponseCode = 5;
            }
        }

        public void OnPost()
        {
            createNew = true;
            CreateUser();
        }

        public void OnPostConfirm()
        {
            createNew = false;
            CreateUser();
        }

        public void OnPostCancel()
        {
            Response.Redirect("http://localhost:4000/Details");
        }

        public void CreateUser()
        {
            string name = Request.Form["username"];
            if (!String.IsNullOrEmpty(name) && !String.IsNullOrWhiteSpace(name))
            {
                Reference refer = new Reference("http://localhost:5000/", new System.Net.Http.HttpClient());
                ResponseCode = refer.RegisterAsync(name).Result;
                if (ResponseCode == 201)
                {
                    if (createNew)
                    {
                        TempData.Add("username", name);
                    }
                    else
                    {
                        TempData["username"] = name;
                    }
                    Output += name + " felhasználó sikeresen létrehozva!";
                }
                else if (ResponseCode == 409)
                {
                    Output += "Hiba\n'" + name + "' nevű felhasználó már létezik!";
                }
                else
                {
                    Output += "Ismeretlen hiba!";
                }
            }
            else
            {
                Output += "Adj meg egy felhasználónevet!";
            }
        }
    }
}

Client/Pages/Transaction.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;

namespace Client.Pages
{
    public class TransactionModel : PageModel
    {

        public string Output { get; private set; } = "";
        public int ResponseCode { get; private set; } = 0;

        public void OnGet()
        {
            if (TempData.Peek("username") == null)
            {
                Output += "Még nem regisztráltál!";
            }
        }
        
        public void OnPostPlus()
        {
            Execute('+');
        }

        public void OnPostMinus()
        {
            Execute('-');
        }
        
        private void Execute(char operation)
        {
            if (TempData.Peek("username") != null)
            {
                int value = int.Parse(Request.Form["ammount"]);
                if (value > 0)
                {
                    string username = TempData.Peek("username").ToString();

                    string url = "";
                    if (operation == '+') url = "http://localhost:5000/add";
                    if (operation == '-') url = "http://localhost:5000/substract";
                    Reference refer = new Reference(url, new System.Net.Http.HttpClient());

                    if (operation == '+') ResponseCode = refer.AddAsync(username, value).Result;
                    if (operation == '-') ResponseCode = refer.SubstractAsync(username, value).Result;

                    if (ResponseCode == 200)
                    {
                        Output += "Sikeres tranzakció!";
                    }
                    else
                    {
                        Output += "Hiba történt!";
                    }
                }
                else
                {
                    Output += "Adj meg egy nem negatív összeget!";
                }
            }
            else
            {
                Output += "Még nem regisztráltál!";
            }
        }
    }
}

Client/Pages/Admin.cshtml
@page
@model Client.Pages.AdminModel
@{
}

<!DOCTYPE html>
<html>
<head>
    <title>Admin</title>
</head>
<body>
    <div class="text-center">
        @{
            if ((Boolean)(TempData.Peek("isAdmin")) == false)
            {
                <form method="post">
                    <fieldset>
                        <legend>Admin</legend>
                        <div>
                            <label for="pass">Jelszó</label>
                            <input id="pass" name="pass" type="text" />
                        </div>
                        <div>
                            <input type="submit" value="Ok" />
                        </div>
                    </fieldset>
                </form>
            } else
            {
                <pre class="text-center">@Model.Output</pre>
            }
        }
    </div>
    <script type="text/javascript">
        document.getElementById("pass").focus();
    </script>
</body>
</html>

Client/Pages/Details.cshtml
@page
@model Client.Pages.DetailsModel
@{
}

<!DOCTYPE html>
<html>
<head>
    <title>Részletek</title>
</head>
<body>
    <div class="text-center">
        @{ 
            if (Model.Status == 1)
            {
                <p>@Model.Output</p>
                <h2>@Model.Balance</h2>
            } else
            {
                <p style="color:red">@Model.Output</p>
            }
        }
    </div>
</body>
</html>

Client/Pages/Index.cshtml
@page
@model Client.Pages.IndexModel
@{
}

<!DOCTYPE html>
<html>
<head>
    <title>Gazdálkodj Okosan</title>
</head>
<body>
    <div class="text-center">
        <h1>Üdv!</h1>
        <h5>Kattints a regisztrálás gombra felül a fiókod létrehozásához!</h5>
    </div>
</body>
</html>

Client/Pages/Register.cshtml
@page
@model Client.Pages.RegisterModel
@{
}
<!DOCTYPE html>
<html>
<head>
    <title>Regisztráció</title>
</head>
<body>
    <div class="text-center">
        @{
            if (Model.ResponseCode == 0)
            {
                <form method="post">
                    <fieldset>
                        <legend>Regisztráció</legend>
                        <div>
                            <label for="username">Felhasználónév</label>
                            <input id="username" name="username" type="text" />
                        </div>
                        <div>
                            <input type="submit" value="Ok" />
                        </div>
                    </fieldset>
                </form>
            }
            else if (Model.ResponseCode == 201)
            {
                <p style="color:forestgreen">@Model.Output</p>
            }
            else if (Model.ResponseCode == 5)
            {
                <form method="post">
                    <fieldset>
                        <legend>Megerősítés</legend>
                        <div>
                            <p>Már regisztráltál @TempData.Peek("username") néven!</p>
                            <p>Szeretnél másik felhsználót létrehozni?</p>
                        </div>
                        <div>
                            <input type="submit" value="Igen" asp-page-handler="Confirm" />
                            <input type="submit" value="Nem" asp-page-handler="Cancel" />
                        </div>
                    </fieldset>
                </form>
            }
            else
            {
                <p style="color:red">@Model.Output</p>
            }
        }
    </div>
    <script type="text/javascript">
        document.getElementById("username").focus();
    </script>
</body>
</html>

Client/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Gazdálkodj</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @{
                            if (String.IsNullOrEmpty((String)TempData.Peek("username")))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-page="/Register">Regisztrálj!</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-page="/Details">Részletek</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-page="/Transaction">Tranzakció</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-page="/Register">@TempData.Peek("username")</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <a asp-page="/Admin">&copy;</a> 2021 - Gazdálkodj
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Client/Pages/Transaction.cshtml
@page
@model Client.Pages.TransactionModel
@{
}
<!DOCTYPE html>
<html>
<head>
    <title>Tranzakció</title>
</head>
<body>
    <div class="text-center">
        @{ if (TempData.Peek("username") != null)
            {
                <form method="post">
                    <fieldset>
                        <legend>Tranzakció</legend>
                        <div>
                            <label for="ammount">Összeg</label>
                            <input id="ammount" name="ammount" type="number" />
                        </div>
                        <div>
                            <input type="submit" value="+" asp-page-handler="Plus" />
                            <input type="submit" value="-" asp-page-handler="Minus" />
                        </div>
                    </fieldset>
                </form>
            }
        }

        @{
            if (Model.ResponseCode == 200)
            {
                <p>@Model.Output</p>
            }
            else
            {
                <p style="color:red">@Model.Output</p>
            }
        }
    </div>
    <script type="text/javascript">
        document.getElementById("ammount").focus();
    </script>
</body>
</html>